config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :applications
  resources :casting_calls
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'casting_calls#index'
end

app/models/application.rb
class Application < ApplicationRecord

  belongs_to :casting_call
  belongs_to :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casting_call.rb
class CastingCall < ApplicationRecord

  has_many :applications
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :casting_calls
  has_many :applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
    @casting_call = CastingCall.new
    @casting_call = CastingCall.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @casting_call = CastingCall.new
    @casting_call = CastingCall.all
  end

  # GET /applications/new
  def new
    @application = Application.new
    @casting_call = CastingCall.new
    @casting_call = CastingCall.all    
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)
    @casting_call = CastingCall.new
    @casting_call = CastingCall.all 

    respond_to do |format|
      if @application.save
        format.html { redirect_to post_path(id: @comment.post_id),
        notice: 'Comment was successfully created.' } 
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:player, :body, :url, :post_id, :user_id)
    end
end

app/controllers/casting_calls_controller.rb
class CastingCallsController < ApplicationController
  before_action :set_casting_call, only: [:show, :edit, :update, :destroy]

  # GET /casting_calls
  # GET /casting_calls.json
  def index
    @casting_calls = CastingCall.all
  end

  # GET /casting_calls/1
  # GET /casting_calls/1.json
  def show
    @application = Application.new
  end

  # GET /casting_calls/new
  def new    
    @casting_call = CastingCall.new
  end

  # GET /casting_calls/1/edit
  def edit
  end

  # POST /casting_calls
  # POST /casting_calls.json
  def create
    @casting_call = CastingCall.new(casting_call_params)

    respond_to do |format|
      if @casting_call.save
        format.html { redirect_to @casting_call, notice: 'Casting call was successfully created.' }
        format.json { render :show, status: :created, location: @casting_call }
      else
        format.html { render :new }
        format.json { render json: @casting_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /casting_calls/1
  # PATCH/PUT /casting_calls/1.json
  def update
    respond_to do |format|
      if @casting_call.update(casting_call_params)
        format.html { redirect_to @casting_call, notice: 'Casting call was successfully updated.' }
        format.json { render :show, status: :ok, location: @casting_call }
      else
        format.html { render :edit }
        format.json { render json: @casting_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casting_calls/1
  # DELETE /casting_calls/1.json
  def destroy
    @casting_call.destroy
    respond_to do |format|
      format.html { redirect_to casting_calls_url, notice: 'Casting call was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_casting_call
      @casting_call = CastingCall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def casting_call_params
      params.require(:casting_call).permit(:name, :info, :post_id, :system, :video, :audio, :studio, :live, :pitch, :seats, :paid, :paid_info, :platform, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/casting_calls_helper.rb
module CastingCallsHelper
end

app/views/applications/_form.html.erb
<%= form_with(model: application, local: true) do |form| %>
  <% if application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
        <% application.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :player %>
    <%= form.text_field :player %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.hidden_field :post_id, value: @casting_call.post_id %>
  </div>  

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Applications</h1>

<table>
  <thead>
    <tr>
      <th>Player</th>
      <th>Body</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.player %></td>
        <td><%= application.body %></td>
        <td><%= application.url %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New Application</h1>

<%= render 'form', application: @application %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player:</strong>
  <%= @application.player %>
</p>

<p>
  <strong>Email:</strong>
  <%= @application.user.email %>
</p>

<p>
  <strong>Body:</strong>
  <%= @application.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @application.url %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/casting_calls/_form.html.erb
<%= form_with(model: casting_call, local: true) do |form| %>
  <% if casting_call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(casting_call.errors.count, "error") %> prohibited this casting_call from being saved:</h2>

      <ul>
        <% casting_call.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_area :info %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :system %>
    <%= form.text_field :system %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.text_field :video %>
  </div>

  <div class="field">
    <%= form.label :audio %>
    <%= form.text_field :audio %>
  </div>

  <div class="field">
    <%= form.label :studio %>
    <%= form.text_field :studio %>
  </div>

  <div class="field">
    <%= form.label :live %>
    <%= form.text_field :live %>
  </div>

  <div class="field">
    <%= form.label :pitch %>
    <%= form.text_field :pitch %>
  </div>

  <div class="field">
    <%= form.label :seats %>
    <%= form.number_field :seats %>
  </div>

  <div class="field">
    <%= form.label :paid %>
    <%= form.text_field :paid %>
  </div>

  <div class="field">
    <%= form.label :paid_info %>
    <%= form.text_field :paid_info %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/casting_calls/edit.html.erb
<h1>Editing Casting Call</h1>

<%= render 'form', casting_call: @casting_call %>

<%= link_to 'Show', @casting_call %> |
<%= link_to 'Back', casting_calls_path %>

app/views/casting_calls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Casting Calls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th>Post</th>
      <th>System</th>
      <th>Video</th>
      <th>Audio</th>
      <th>Studio</th>
      <th>Live</th>
      <th>Pitch</th>
      <th>Seats</th>
      <th>Paid</th>
      <th>Paid info</th>
      <th>Platform</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @casting_calls.each do |casting_call| %>
      <tr>
        <td><%= casting_call.name %></td>
        <td><%= casting_call.info %></td>
        <td><%= casting_call.post_id %></td>
        <td><%= casting_call.system %></td>
        <td><%= casting_call.video %></td>
        <td><%= casting_call.audio %></td>
        <td><%= casting_call.studio %></td>
        <td><%= casting_call.live %></td>
        <td><%= casting_call.pitch %></td>
        <td><%= casting_call.seats %></td>
        <td><%= casting_call.paid %></td>
        <td><%= casting_call.paid_info %></td>
        <td><%= casting_call.platform %></td>
        <td><%= link_to 'Show', casting_call %></td>
        <td><%= link_to 'Edit', edit_casting_call_path(casting_call) %></td>
        <td><%= link_to 'Destroy', casting_call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Casting Call', new_casting_call_path %>

app/views/casting_calls/new.html.erb
<h1>New Casting Call</h1>

<%= render 'form', casting_call: @casting_call %>

<%= link_to 'Back', casting_calls_path %>

app/views/casting_calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @casting_call.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @casting_call.user.email %>
</p>

<p>
  <strong>Info:</strong>
  <%= @casting_call.info %>
</p>

<p>
  <strong>Post:</strong>
  <%= @casting_call.post_id %>
</p>

<p>
  <strong>System:</strong>
  <%= @casting_call.system %>
</p>

<p>
  <strong>Video:</strong>
  <%= @casting_call.video %>
</p>

<p>
  <strong>Audio:</strong>
  <%= @casting_call.audio %>
</p>

<p>
  <strong>Studio:</strong>
  <%= @casting_call.studio %>
</p>

<p>
  <strong>Live:</strong>
  <%= @casting_call.live %>
</p>

<p>
  <strong>Pitch:</strong>
  <%= @casting_call.pitch %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @casting_call.seats %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @casting_call.paid %>
</p>

<p>
  <strong>Paid info:</strong>
  <%= @casting_call.paid_info %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @casting_call.platform %>
</p>

<div id="applications">
  <%= render 'applications/form', application: @application %>
</div>

<%= link_to 'Edit', edit_casting_call_path(@casting_call) %> |
<%= link_to 'Back', casting_calls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rpgcastingcall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>